name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution (Release | x64)
      run: msbuild HotkeyManager.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143 /t:Rebuild
